### PR TITLE
Fix bug when convert raw gyro data to rad/s

### PR DESCRIPTION
**Pull request by tfx2001**

### CODE REVIEW

**Comment by juliangaal** [comment]
What is your source for this change?

**Comment by tfx2001** [comment]
When I use `get_gyro()`, the range of results looks a bit strange. Then I tried to derive it myself and found that it was a algorithm problem.



After this change, I use the result in Madgwick fusion and it works good.

**Comment by juliangaal** [comment]
How did you setup madgwick fusion and/or could you post before and after? Thanks!

Which revision of the manual did you get the image above from? Or is it some other source?

**Comment by tfx2001** [comment]
> How did you setup madgwick fusion and/or could you post before and after? Thanks!
> 
> Which revision of the manual did you get the image above from? Or is it some other source?

I'm sorry, I don't have a record of before and after changes. And the formula above is my own derivation. If I have misunderstood, please point it out and apologize for that.

**Comment by juliangaal** [comment]
no worries, I am not 100% sure myself.

Which madgwick filter package did you use? I'll check it out as soon as I can, prob Christmas Break

**Comment by tfx2001** [comment]
The AHRS package I use:

```toml
[dependencies]
ahrs = "0.4"
```

And here is my test code: [main.rs](https://gist.github.com/tfx2001/b661bc49474afbfa22f93a4cf22159b1)

**Comment by juliangaal** [comment]
perfekt, thank you!

**Comment by HeikoRibberink** [comment]
Can you please still push this branch to master, and push to crates.io?

**Comment by juliangaal** [comment]
> Can you please still push this branch to master, and push to crates.io?

I haven't been able to verify myself (yet). Can you confirm that the issue raised is correct? **Not suggesting it isn't** @tfx2001, I would just be more comfortable testing it out for myself, as well.

**Comment by juliangaal** [comment]
You are absolutely correct in your assessment @tfx2001.

The confusion for me arose in the way I apply "sensitivity", basically the inverse "resolution". 

According to the datasheet, depending on the scale configuration of the gyroscope, the data needs to be scaled, like this:

```
250DPS => 250.0 / 32768.0,
500DPS => 500.0 / 32768.0,
1000DPS => 1000.0 / 32768.0,
2000DPS => 2000.0 / 32768.0,
```

`RAW_DATA * (!) FACTOR` is the default scaling. I tried to save some calculations and saved results of this scaling factor as the "sensitivity"

```rust
// 32768.0 / 250.0, ....
pub const GYRO_SENS: (f32, f32, f32, f32) = (131., 65.5, 32.8, 16.4);
```

of course, this "sensitvity" must be applied my **dividing**, exactly as you have found.

Thanks again, I will merge and publish to crates.io.

**Comment by juliangaal** [comment]
done

**Pull request merged**
